Drop support for Python 3.4.  No code changes.
Travis said:
ERROR: This lxml version requires Python 2.7, 3.5 or later.

I see no need to spend time supporting 3.4 anymore.