Add mx.ini, use lxml 6.0.2.
There are two failures.

First failure:

```
Failure in test testAll (diazo.tests.test_diazo.Test-copy.testAll)
Traceback (most recent call last):
  File "/Users/maurits/.local/share/uv/python/cpython-3.13.3-macos-aarch64-none/lib/python3.13/unittest/case.py", line 58, in testPartExecutor
    yield
  File "/Users/maurits/.local/share/uv/python/cpython-3.13.3-macos-aarch64-none/lib/python3.13/unittest/case.py", line 651, in run
    self._callTestMethod(testMethod)
  File "/Users/maurits/.local/share/uv/python/cpython-3.13.3-macos-aarch64-none/lib/python3.13/unittest/case.py", line 606, in _callTestMethod
    if method() is not None:
  File "/Users/maurits/community/plone-coredev/6.2/src/diazo/src/diazo/tests/test_diazo.py", line 238, in testAll
    assert self.themed_content.xpath(
AssertionError: /Users/maurits/community/plone-coredev/6.2/src/diazo/src/diazo/tests/copy/xpaths.txt: /html/head/title = 'A Deeper Look At diazo'
```

Going in with a pdb says:

```
(Pdb) self.themed_content.xpath("/html/head/title")[0].text
'<title>A Deeper Look At diazo'
(Pdb) print(etree.tounicode(self.themed_content))
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xmlns="http://www.w3.org/1999/xhtml">
    <head><meta http-equiv="Content-Type" content="text/html; charset=UTF-8" /><title id="something">&lt;title&gt;A Deeper Look At diazo</title>
    </head>
    <body></body>
</html>
```

So we are getting an escaped title tag within the title tag.

Second failure:

```
Error in test test_content_empty (diazo.tests.test_wsgi.TestXSLTMiddleware.test_content_empty)
Traceback (most recent call last):
  File "/Users/maurits/.local/share/uv/python/cpython-3.13.3-macos-aarch64-none/lib/python3.13/unittest/case.py", line 58, in testPartExecutor
    yield
  File "/Users/maurits/.local/share/uv/python/cpython-3.13.3-macos-aarch64-none/lib/python3.13/unittest/case.py", line 651, in run
    self._callTestMethod(testMethod)
  File "/Users/maurits/.local/share/uv/python/cpython-3.13.3-macos-aarch64-none/lib/python3.13/unittest/case.py", line 606, in _callTestMethod
    if method() is not None:
  File "/Users/maurits/community/plone-coredev/6.2/src/diazo/src/diazo/tests/test_wsgi.py", line 351, in test_content_empty
    response = request.get_response(app)
  File "/Users/maurits/community/plone-coredev/6.2/src/diazo/.tox/test/lib/python3.13/site-packages/webob/request.py", line 1313, in send
    status, headers, app_iter = self.call_application(
  File "/Users/maurits/community/plone-coredev/6.2/src/diazo/.tox/test/lib/python3.13/site-packages/webob/request.py", line 1278, in call_application
    app_iter = application(self.environ, start_response)
  File "/Users/maurits/community/plone-coredev/6.2/src/diazo/src/diazo/wsgi.py", line 321, in __call__
    serializer = getHTMLSerializer(
  File "/Users/maurits/community/plone-coredev/6.2/src/diazo/.tox/test/lib/python3.13/site-packages/repoze/xmliter/utils.py", line 26, in getHTMLSerializer
    serializer = getXMLSerializer(
  File "/Users/maurits/community/plone-coredev/6.2/src/diazo/.tox/test/lib/python3.13/site-packages/repoze/xmliter/utils.py", line 19, in getXMLSerializer
    return XMLSerializer(root.getroottree(), serializer, pretty_print, doctype=doctype)
AttributeError: 'NoneType' object has no attribute 'getroottree'
```

This is in a test where we check what happens with an empty response.
On our side in `wsgi.py` this is the part where the exception is raised:

```
            # Prepare the serializer
            try:
                serializer = getHTMLSerializer(
                    response.app_iter,
                    encoding=input_encoding,
                )
            except etree.XMLSyntaxError:
                # Abort transform on syntax error for empty response
                # Headers should be left intact
                return response(environ, start_response)
```

So we already catch an error that we expect for an empty response, but now we get a different error.
Maybe we should catch the new `AttributeError` as well, but that sounds a bit broad, and may ignore totally different errors.
Maybe this needs a fix in `repoze.xmliter`.